// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProgramlamaAraProje.Models;

namespace WebProgramlamaAraProje.Migrations
{
    [DbContext(typeof(CollageDbContext))]
    [Migration("20221120114927_CollageDB")]
    partial class CollageDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebProgramlamaAraProje.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminKullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WebProgramlamaAraProje.Models.Announcement", b =>
                {
                    b.Property<int>("DuyuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DuyuruBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuyuruIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuyuruTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("DuyuruID");

                    b.ToTable("Announcements");
                });
#pragma warning restore 612, 618
        }
    }
}
